#! /bin/tcsh -f

# This the main NetMHCpan 4.2 script. It only acts as the frontend to the
# software proper, a compiled binary.
# 
# VERSION:	2019 Dec 9 launch
# 

###############################################################################
#               GENERAL SETTINGS: CUSTOMIZE TO YOUR SITE
###############################################################################

# full path to the NetMHCpan 4.2 directory (mandatory)
setenv NMHOME /Users/trastogi/ExtremeSSD/neoantigen-target-discovery/tools/netMHCpan-4.2

# determine where to store temporary files (must be writable to all users)

if ( ${?TMPDIR} == 0 ) then
	setenv  TMPDIR  /tmp
endif

# determine platform (do not change this unless you don't have 'uname'!)
setenv	UNIX	`uname -s`
setenv	AR	`uname -m`

###############################################################################
#               NOTHING SHOULD NEED CHANGING BELOW THIS LINE!
###############################################################################

# other settings
set PLATFORM = `echo $UNIX $AR | awk '{print $1"_"$2}'`
setenv NETMHCpan $NMHOME/$PLATFORM
setenv DTUIBSWWW www
setenv NetMHCpanWWWPATH /services/NetMHCpan/tmp/
setenv NetMHCpanWWWDIR /usr/opt/www/pub/CBS/services/NetMHCpan/tmp

# main ========================================================================
if ( -x $NETMHCpan/bin/netMHCpan-4.2 ) then
   $NETMHCpan/bin/netMHCpan-4.2 $*
else
   echo netMHCpan: no binaries found for $PLATFORM $NETMHCpan/bin/netMHCpan
endif

# end of script ===============================================================
